fees_info = (
    'IOF',

    'TAXA DE ADMINISTRACAO',
    'TAXA CETIP (AJUSTE)',
    'TAXA CETIP (ESTORNO)',

    'TAXA DE CUSTODIA',
    'TAXA DE CONTROLADORIA',

    'TAXA DE CONTROLADORIA (REMUNERACAO VARIAVEL)',
    'TAXA DE CUSTODIA (REMUNERACAO VARIAVEL)',

    'TAXA SELIC (AJUSTE)',

    'TARIFA DE LIQUIDACAO FINANCEIRA (AJUSTE)',
    'TARIFA DE LIQUIDACAO FINANCEIRA (DESPESA B 10)',

    'DESPESA DE CUSTO SELIC',
    'CUSTO CETIP',
)