fund_name_mapping = {
    #Taxas
    'TX DE CONTROLADORIA S/ TX DE ADMIN. [BBDC] BRUTA': 'TAXA DE CONTROLADORIA',
    'TX DE CONTROLADORIA S/ TX DE ADMIN. [BBDC] APROPRIADA': 'TAXA DE CONTROLADORIA',
    'TAXA DE CONTROL. S/ TX.*': 'TAXA DE CONTROLADORIA',
    'TX CUSTODIA BRUTA.*': 'TAXA DE CUSTODIA',
    'TAXA DE CUSTODIA A PAGAR.*': 'TAXA DE ADMINISTRACAO',
    'TAXA DE CUSTODIA BRUTA': 'TAXA DE CUSTODIA',
    'TAXA DE CUSTODIA APROPRIADA': 'TAXA DE CUSTODIA',

    #Despesas
    'CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'DESPESA DE CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'TARIFA DE LIQUIDACAO FINANCEIRA' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'APLICACAO - TARIFA DE LIQUIDACAO FINANCEIRA': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'DESPESA DE CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'DESPESA DE B 10 - TARIFA DE LIQUIDACAO FINANCEIRA.*': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'Despesa de B 10 - TARIFA DE LIQUIDAÇÃO FINANCEIRA': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',

    #Ajuste
    'AJUSTE DE TARIFA DE LIQUIDACAO FINANCEIRA' : '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    'AJUSTE DE TAXA CETIP' : '(AJUSTE) TAXA CETIP',
    'AJUSTE TAXA CETIP.*' : '(AJUSTE) TAXA CETIP',

    #Fundos
    'ALTERNATIVOS MIR FIM': 'ALTERNATIVOS MIRANTE FICM',
    'BB ACOES GLOBAIS FIA': 'BB ACOES GL HEDGE IE',
    'FIC DE FI ACOES IBRX': 'FIC DE FI AÇÕES IBRX',

    #Estorno
    # 'ESTORNO TAXA CETIP' : 'ESTORNO DE TAXA CETIP'

    #Tarifas
    #'Tarifa de Liquidacao Financeira' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',

    #
    r'IOF .*': 'IOF',
    "17760": "017760",

}









