fund_name_mapping = {
    # Taxas
    r'^TX DE CONTROLADORIA.*$': 'TAXA DE CONTROLADORIA',
    r'^TAXA DE CONTROL\.? S/ TX.*$': 'TAXA DE CONTROLADORIA',
    r'^TX CUSTODIA BRUTA.*$': 'TAXA DE CUSTODIA',
    r'^TAXA DE CUSTODIA A PAGAR.*$': 'TAXA DE ADMINISTRACAO',
    r'^TAXA DE CUSTODIA BRUTA$': 'TAXA DE CUSTODIA',
    r'^TAXA DE CUSTODIA APROPRIADA$': 'TAXA DE CUSTODIA',

    # Despesas
    r'^DESPESA DE CUSTO CETIP.*$': 'DESPESA - CUSTO CETIP',
    r'^CUSTO CETIP.*$': 'DESPESA - CUSTO CETIP',
    r'^DESPESA DE B 10 - TARIFA DE LIQUIDACAO FINANCEIRA.*$': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    r'^APLICACAO - TARIFA DE LIQUIDACAO FINANCEIRA$': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    r'^TARIFA DE LIQUIDACAO FINANCEIRA$': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',

    # Ajuste
    r'^AJUSTE DE TARIFA DE LIQUIDACAO FINANCEIRA$': '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    r'^AJUSTE DE TAXA CETIP$': '(AJUSTE) TAXA CETIP',
    r'^AJUSTE TAXA CETIP.*$': '(AJUSTE) TAXA CETIP',

    # Fundos
    r'^ALTERNATIVOS MIR FIM$': 'ALTERNATIVOS MIRANTE FICM',
    r'^BB ACOES GLOBAIS FIA$': 'BB ACOES GL HEDGE IE',
    r'^FIC DE FI ACOES IBRX$': 'FIC DE FI ACOES IBRX',

    # IOF
    r'^IOF .*$': 'IOF',
    r'^17760$': '017760',
}
