""""Mapping for expenses descriptions to standardized expense categories."""
expenses_mapping = {
    'TX DE CONTROLADORIA S/ TX DE ADMIN.*': 'TAXA DE CONTROLADORIA',
    'TAXA DE CONTROL. S/ TX.*': 'TAXA DE CONTROLADORIA',

    '.*CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'TX CUSTODIA BRUTA.*': 'TAXA DE CUSTODIA',
    'TAXA DE CUSTODIA A PAGAR.*': 'TAXA DE ADMINISTRACAO',
    'TAXA DE CUSTODIA BRUTA.*': 'TAXA DE CUSTODIA',
    r'IOF .*': 'IOF',
    #'DESPESA DE B 10.*': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',

    'AJUSTE DE TARIFA DE LIQUIDACAO FINANCEIRA*' : '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    'AJUSTE DE TAXA CETIP*' : '(AJUSTE) TAXA CETIP',
    'AJUSTE TAXA CETIP*' : '(AJUSTE) TAXA CETIP',
    #'Tarifa de Liquidacao Financeira' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'TARIFA DE LIQUIDACAO FINANCEIRA' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'APLICACAO - TARIFA DE LIQUIDACAO FINANCEIRA': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    #'Ajuste de TARIFA DE LIQUIDACAO FINANCEIRA' : '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    #'Despesa de B 10 - TARIFA DE LIQUIDAÇÃO FINANCEIRA': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    #'ESTORNO TAXA CETIP' : 'ESTORNO DE TAXA CETIP'
}
