fees_info = (
    'IOF',

    'TAXA ADMINISTRACAO',
    'TAXA CETIP',
    'TAXA DE CUSTODIA',
    'TAXA DE CONTROLADORIA'

    '(AJUSTE) TAXA CETIP',
    'AJUSTE DE TAXA SELIC',
    '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',

    'DESPESA DE CUSTO SELIC',
    'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'DESPESA - CUSTO CETIP',

    )
