fees_info = (
    'IOF',
    'TAXA ADMINISTRACAO',
    'TAXA CETIP',

    '(AJUSTE) TAXA CETIP',
    'AJUSTE DE TAXA SELIC',
    'DESPESA DE CUSTO SELIC',

    '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'DESPESA - CUSTO CETIP',
    'TAXA DE CUSTODIA',
    'TAXA DE CONTROLADORIA'
    )