rename_datas = {
    'ALTERNA MIRANTE FICM': 'ALTERNATIVOS MIR FIM',
    'BB ACOES GL HEDGE IE': 'BB ACOES GLOBAIS FIA',
    'FIC DE FI AÇÕES IBRX': 'FIC DE FI ACOES IBRX',
    'TX DE CONTROLADORIA S/ TX DE ADMIN.*': 'TAXA DE CONTROLADORIA',
    'TAXA DE CONTROL. S/ TX.*': 'TAXA DE CONTROLADORIA',

    '.*CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'TX CUSTODIA BRUTA.*': 'TAXA DE CUSTODIA',
    'TAXA DE CUSTODIA A PAGAR.*': 'TAXA DE ADMINISTRACAO',
    'TAXA DE CUSTODIA BRUTA.*': 'TAXA DE CUSTODIA',
    r'IOF .*': 'IOF',
    r'DESPESA DE B 10.*': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    "17760": "017760",

    'AJUSTE DE TARIFA DE LIQUIDACAO FINANCEIRA*' : '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    'AJUSTE DE TAXA CETIP*' : '(AJUSTE) TAXA CETIP',
    'AJUSTE TAXA CETIP*' : '(AJUSTE) TAXA CETIP'
    #'ESTORNO TAXA CETIP' : 'ESTORNO DE TAXA CETIP'
}
