rename_datas = {
    'ALTERNA MIRANTE FICM': 'ALTERNATIVOS MIR FIM',
    'BB ACOES GL HEDGE IE': 'BB ACOES GLOBAIS FIA',
    'FIC DE FI AÇÕES IBRX': 'FIC DE FI ACOES IBRX',
    'TX DE CONTROLADORIA S/ TX DE ADMIN. [BBDC] BRUTA': 'TAXA DE CONTROLADORIA',
    'TX DE CONTROLADORIA S/ TX DE ADMIN. [BBDC] APROPRIADA': 'TAXA DE CONTROLADORIA',
    'TAXA DE CONTROL. S/ TX.*': 'TAXA DE CONTROLADORIA',
    'CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'DESPESA DE CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'TX CUSTODIA BRUTA.*': 'TAXA DE CUSTODIA',
    'TAXA DE CUSTODIA A PAGAR.*': 'TAXA DE ADMINISTRACAO',
    'TAXA DE CUSTODIA BRUTA': 'TAXA DE CUSTODIA',
    'TAXA DE CUSTODIA APROPRIADA': 'TAXA DE CUSTODIA',
    r'IOF .*': 'IOF',
   # 'DESPESA DE B 10': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    "17760": "017760",
    'AJUSTE DE TARIFA DE LIQUIDACAO FINANCEIRA' : '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    'AJUSTE DE TAXA CETIP' : '(AJUSTE) TAXA CETIP',
    'AJUSTE TAXA CETIP.*' : '(AJUSTE) TAXA CETIP',
    #'Tarifa de Liquidacao Financeira' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'TARIFA DE LIQUIDACAO FINANCEIRA' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'APLICACAO - TARIFA DE LIQUIDACAO FINANCEIRA': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    'DESPESA DE CUSTO CETIP.*': 'DESPESA - CUSTO CETIP',
    'DESPESA DE B 10 - TARIFA DE LIQUIDACAO FINANCEIRA.*' : 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
    #'Ajuste de TARIFA DE LIQUIDACAO FINANCEIRA' : '(AJUSTE) TARIFA DE LIQUIDACAO FINANCEIRA',
    #'ESTORNO TAXA CETIP' : 'ESTORNO DE TAXA CETIP'
    'Despesa de B 10 - TARIFA DE LIQUIDAÇÃO FINANCEIRA': 'DESPESA B 10 - TARIFA DE LIQUIDACAO FINANCEIRA',
}

#AJUSTE DE TARIFA DE LIQUIDACAO FINANCEIRA
#Despesa de B 10 - TARIFA DE LIQUIDAÇÃO FINANCEIRA
#Despesa de CUSTO CETIP