import pandas as pd

patroc_code = {
    "001": "Patrocinadoras", # código universal
    "002": ["FIBRASIL INFRAESTRUTURA E FIBRA OTICA SA (VM)", "FIBRASIL INFRAESTRUTURA E FIBRA OTICA SA (VT)"],
    "003": ["FUNDACAO TELEFONICA (VT)", "FUNDACAO TELEFONICA (VM)"],
    "004": ["SP TELECOMUNICACOES PARTICIPACOES LTDA (P)", "SP TELECOMUNICACOES PARTICIPACOES LTDA (VT)"],
    "005": ["TELEFONICA BRASIL SA (VM)", "TELEFONICA BRASIL SA (BD)", "TELEFONICA BRASIL SA (VT)", "TELEFONICA BRASIL SA (P)"],
    "006": ["TELEFONICA CIBERSEGURANCA E TECNOLOGIA DO BRASIL LTDA (VT)", "TELEFONICA CIBERSEGURANCA E TECNOLOGIA DO BRASIL LTDA (VM)"],
    "007": ["TELEFONICA CLOUD E TECNOLOGIA DO BRASIL SA (VM)", "TELEFONICA CLOUD E TECNOLOGIA DO BRASIL SA (VT)"],
    "008": ["TELEFONICA CORRETORA DE SEGUROS LTDA (P)", "TELEFONICA CORRETORA DE SEGUROS LTDA (VM)"],
    "009": ["TELEFONICA GLOBAL SOLUTIONS BRASIL LTDA (VM)", "TELEFONICA GLOBAL SOLUTIONS BRASIL LTDA (VT)"],
    "010": "TELEFONICA INFRAESTRUTURA E SEGURANCA LTDA (VM)",
    "011": ["TELEFONICA IOT BIG DATA E TECNOLOGIA DO BRASIL SA (VT)", "TELEFONICA IOT BIG DATA E TECNOLOGIA DO BRASIL SA (VM)"],
    "012": "TELEFONICA ON THE SPOT SOLUCOES DIGITAIS DO BRASIL LTDA (VM)",
    "013": ["TELEFONICA SERVICOS EMPRESARIAIS DO BRASIL LTDA (VT)", "TELEFONICA SERVICOS EMPRESARIAIS DO BRASIL LTDA (P)"],
    "014": ["TELEFONICA TRANSPORTES E LOGISTICA LTDA (VT)", "TELEFONICA TRANSPORTES E LOGISTICA LTDA (VM)"],
    "015": ["TELXIUS CABLE BRASIL LTDA (VT)", "TELXIUS CABLE BRASIL LTDA (VM)"],
    "016": "TERRA NETWORKS BRASIL S/A (VM)",
    "017": ["VISAO PREV SOCIEDADE DE PREVIDENCIA COMPLEMENTAR (VM)", "VISAO PREV SOCIEDADE DE PREVIDENCIA COMPLEMENTAR (VT)", "VISAO PREV SOCIEDADE DE PREVIDENCIA COMPLEMENTAR (P)"],
    "018": ["VITA IT COMÉRCIO E SERVIÇOS DE SOLUÇÕES EM TI LTDA (VT)", "VITA IT COMÉRCIO E SERVIÇOS DE SOLUÇÕES EM TI LTDA (VM)"],
    "019": ["MAIS VISAO"]
}

def transform_reservas(df):
    df = df.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))
    df['Patrocinadora'] = df["Razao social"].map(lambda x: next((key for key, value in patroc_code.items() if x in value), "001") if isinstance(x, str) else "001")
    
    return df